version: "2"
services:
  server:
    build:
      context: ./server/
      dockerfile: Dockerfile-prod

  client:
    build:
      context: .
      dockerfile: Dockerfile-prod
    ports:
      - 80:80
    depends_on:
      - server
