version: "2"
services:
  server:
    build:
      context: ./server/
    command: python main.py
    volumes:
      - ./server/:/usr/app/server
    ports:
      - "3000:3000"

  client:
    build:
      context: ./client/
    command: yarn dev
    volumes:
      - ./client/:/usr/app/client
      - /usr/app/client/node_modules
    depends_on:
      - server
    ports:
      - "5000:5000"
      - "35729:35729"
    environment:
      - NODE_ENV=development
